### ISSUE TITLE
Python script

### ISSUE THREAD

**Issue by gabays** [katabase/2_CleanedData#2]
Problems when running script:
```console
my_env) (base) gabays@gabays-computer:~/dev/katabase/2_CleanedData$ python3 script/extractor_xml.py 301-400/Add/
Traceback (most recent call last):
  File "script/extractor_xml.py", line 7, in <module>
    import dateparser
ModuleNotFoundError: No module named 'dateparser'
```
```console
(my_env) (base) gabays@gabays-computer:~/dev/katabase/2_CleanedData$ python3 script/extractor_xml.py 301-400/Add/
Traceback (most recent call last):
  File "script/extractor_xml.py", line 10, in <module>
    import tables.rep_greg_conversion
  File "/home/gabays/dev/katabase/2_CleanedData/script/tables/rep_greg_conversion.py", line 6, in <module>
    with open("tables/corresp_table.json", "r") as corresp_table:
FileNotFoundError: [Errno 2] No such file or directory: 'tables/corresp_table.json'
```

**Comment by gabays** [comment]
Better to let is open since it is not solved yet.

**Comment by alexbartz** [comment]
Second part of the issue is resolved by the commit.
For the first part, I tested it on Mac and Linux and both worked. 
My guess is that you didn't install the requirements of **this** repo...
